# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_url', models.FloatField()),
                ('tf_value', models.FloatField()),
                ('tf_label', models.BooleanField()),
                ('human_label', models.BooleanField()),
            ],
        ),
    ]
