# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galaxy',
            name='file_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='human_label',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='tf_label',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='galaxy',
            name='tf_value',
            field=models.FloatField(null=True),
        ),
    ]
